#### Numpy

- Numpy is a fundamental library for scientific computing in python.

- It provides support for arrays and matrices, along with a collection of mathematical functions to operate in these Data Structures


In [1]:
## Python

!pip install numpy


[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
## Arrays and matrices
import numpy as np

## Create arrays using Numpy
# Create 1D Array - 1 Braces opens and closes

ar1 = np.array([1,2,3,4,5])
print(ar1)
print(type(ar1))
print(ar1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## Reshape to 2D array
## 2D - 2 Braces opens and 2 braces closes

ar2 = np.array([1,2,3,4,5])
ar2.reshape((1, 5))  # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
# 2D Array
ar2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(ar2)
print(ar2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
## Create arrays with in built function

np.arange(0,10,2).reshape(1, 5)

array([[0, 2, 4, 6, 8]])

In [ ]:
## Create arrays with in built function
# Convert 1D to 2D
np.arange(0,10,2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
## 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
## Identify matrix
# ALl diagonal elements will be 1 and the remaining 0

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# Create a 5 x 5 matix with elements from 1 to 25
five_matrix = np.arange(1, 26).reshape(5,5)
print(five_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
## Creating an array with evenly spaced values within a given interval
even_arr = np.arange(0,20, 2)
print(even_arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [23]:
## Attributes of numpy Arrays

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)

## Shape of Array
print("Shape: ", arr.shape)

## Number of Dimensions
print("Number of Dimensions: ", arr.ndim)

## Array size
print("Size (number of elements): ", arr.size)

## Array Data Type
print("Date Type: ", arr.dtype)

## Array Item Size
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimensions:  2
Size (number of elements):  6
Date Type:  int64
Item size (in bytes): 8


In [24]:
## Numpy Vectorized Operation

ar = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])

## Element wise Addition
print("Addition:", ar1+ar2)

## Element wise substraction
print("Substraction: ", ar1-ar2)

## Element wise Multiplication
print("Multiplication: ", ar1*ar2)

## Element wise Division
print("Division: ", ar1/ar2)

Addition: [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function (ufuncs) - Some function that applies to the entire array

arr = np.array([2,3,4,5,6])

## Squareroot
print(np.sqrt(arr))

## Exponantial
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
## Array Slicing and Indexing 

## Slicing

ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", ar)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
## Accessing single element from array
# 
ar[0][0]

np.int64(1)

In [ ]:
## Columns
ar[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
## Second row to the end
ar[2:]

array([[ 9, 10, 11, 12]])

In [37]:
## Columns
ar[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
##
print(ar[0][0])
print(ar[0:2,2:])  

1
[[3 4]
 [7 8]]


In [43]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", ar)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
## Pick up 6,7,10,11

print(ar[1:,1:3])

[[ 6  7]
 [10 11]]


In [46]:
## Modify array element

ar[0,0]=100
print(ar)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [47]:
## Replace column one

ar[1:]=100
print(ar)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Statistical Concepts - Normalization

    Normalization - Change the data to have mean of 0 and standard deviation of 1.

In [49]:
## Normalization

data = np.array([1,2,3,4,5])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
norm = (data - mean)/std_dev
print(f"Normalization: {norm}")

## Variance
var = np.var(data)
print(f"Variance: {var}")

Normalization: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance: 2.0


In [50]:
## Mean, Median, Standard Deviation and Variance

dt = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(dt)
print("Mean: ", mean)

## Median
median = np.median(dt)
print("Median: ", median)

## Standard Deviation
dev = np.std(dt)
print("Standard Deviation: ", dev)

## Variance
var = np.var(dt)
print(f"Variance: {var}")

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance: 8.25


In [52]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Retrieving data greater than 5
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [56]:
# Retrieving data greater than 5
data[(data > 5) & (data<=8)]

array([6, 7, 8])