# Module: NumPy Assignments
## Lesson: NumPy







### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [1]:
import numpy as np

d = np.random.randint(1, 21, size=(5,5))
print("Original Array:\n", d)

# Replace all elements in 3rd column with 1
d[:, 2]= 1
print("Modified Array:\n", d)

Original Array:
 [[ 8 12  1 18  6]
 [14 13  5 19  5]
 [ 2 13 19 16  1]
 [14 20 10  8  9]
 [ 1  2  2  4 20]]
Modified Array:
 [[ 8 12  1 18  6]
 [14 13  1 19  5]
 [ 2 13  1 16  1]
 [14 20  1  8  9]
 [ 1  2  1  4 20]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
##
ar = np.arange(1, 17).reshape((4, 4))
print("Array:\n", ar)

## Replace diagonal elements with 0
np.fill_diagonal(ar, 0)
print("Modified Array:\n", ar)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [5]:
##
arr = np.arange(1, 37).reshape((6, 6))
print("Original Array:\n", arr)

## Extract sb-array consisting 3rd to 5th and 2nd to 4th column
sub_ar = arr[2:5, 1:4]
print("Sub Array:\n", sub_ar)

Original Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [7]:
##
ar = np.random.randint(1, 26, size=(5, 5))
print("Random Integers:\n", ar)

## Extract elements at the border
brd_elm = np.concatenate((ar[0, :], ar[-1, :], ar[1:-1, 0], ar[1:-1, -1]))
print("Border Elements:\n", brd_elm)

Random Integers:
 [[10 24 10  4 13]
 [ 7 17  5  1 22]
 [11 24 18 21 19]
 [21 12 21 23 21]
 [16 24 25 23  1]]
Border Elements:
 [10 24 10  4 13 16 24 25 23  1  7 11 21 22 19 21]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.



In [8]:
##

ar1 = np.random.randint(1, 13, size=(3,4))
ar2 = np.random.randint(1, 13, size=(3,4))
print("First Random Array:\n", ar1)
print("Second Random Array:\n", ar2)

## Element wise Operations
addition = ar1 + ar2
subtraction = ar1 - ar2
multiply = ar1 * ar2
division = ar1 / ar2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiply)
print("Element-wise division:")
print(division)

First Random Array:
 [[ 3  6 10  7]
 [ 6  2  7  8]
 [ 6  1  3  3]]
Second Random Array:
 [[ 6  7  3  8]
 [11 10 12  9]
 [ 9 12  4  8]]
Element-wise addition:
[[ 9 13 13 15]
 [17 12 19 17]
 [15 13  7 11]]
Element-wise subtraction:
[[ -3  -1   7  -1]
 [ -5  -8  -5  -1]
 [ -3 -11  -1  -5]]
Element-wise multiplication:
[[18 42 30 56]
 [66 20 84 72]
 [54 12 12 24]]
Element-wise division:
[[0.5        0.85714286 3.33333333 0.875     ]
 [0.54545455 0.2        0.58333333 0.88888889]
 [0.66666667 0.08333333 0.75       0.375     ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
## 0 = rows because row index starts at 0
## 1 = columns because column index is the second dimension

array = np.arange(1, 17).reshape(4, 4)
print("Array")
print(array)

## Perform row-wise and column-wise sum
rw_sum = np.sum(array, axis=0)  # axis=0 affects the Rows
clm_sum = np.sum(array, axis=1) # axis = 1 affects columns

print("Row wise sum is:\n", rw_sum)
print("Column wise sum is:\n", clm_sum)

Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum is:
 [28 32 36 40]
Column wise sum is:
 [10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [12]:
## Random Integers

ar = np.random.randint(1, 26, size=(5, 5))
print("Random Array Integers:\n", ar)

## Operation
mn = np.mean(ar)
md = np.median(ar)
std_dev = np.std(ar)
var = np.var(ar)

print("Mean of Array:\n", mn)
print("Median of Array:\n", md)
print("Standard Deviation:\n", std_dev)
print("Variance of Array is:\n", var)

Random Array Integers:
 [[14 15  6 15  2]
 [13  9 20 15  9]
 [23 19 21 15 24]
 [24 16  9 17 24]
 [19 15 18 12  2]]
Mean of Array:
 15.04
Median of Array:
 15.0
Standard Deviation:
 6.18048541782925
Variance of Array is:
 38.1984


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [13]:
##
arr = np.arange(1, 10).reshape(3, 3)
print("Original array is:\n", arr)

# Normalization
mean = np.mean(arr)
std_dev = np.std(arr)
norm = (arr - mean) / std_dev
print("Normalization:\n", norm)

Original array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalization:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [15]:
## 
arr = np.random.randint(1, 19, size=(3, 3))
row_arr = np.random.randint(1, 19, size=(3,))
print("Random Array is:\n", arr)
print("1D Array of Shape:\n", row_arr)

# Add the 1D array to each row of the 2D array using broadcasting
res = arr + row_arr
print("1D of 2D Array:\n", res)

Random Array is:
 [[16  6 12]
 [ 5  9 13]
 [ 5 11 13]]
1D Array of Shape:
 [ 4 12  1]
1D of 2D Array:
 [[20 18 13]
 [ 9 21 14]
 [ 9 23 14]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
# Create a NumPy array of shape (4, 4) filled with random integers
ar = np.random.randint(1, 17, size=(4, 4))
col_ar = np.random.randint(1, 17, size=(4,))
print("Original Array is:\n", ar)
print("1D Array:\n", col_ar)

# Subtract the 1D array from each column of the 2D array using broadcasting
# np.newaxis
# adds a new dimension to an array (used to convert 1D → 2D or expand shape)

result = ar - col_ar[:, np.newaxis]  ## Add one more axis, e.g (5,)to (5,1)
print("Subtracted Array:\n", result)

Original Array is:
 [[ 4  1  4 10]
 [ 5 10  6 11]
 [14  2  4 16]
 [12  9  7  1]]
1D Array:
 [11 13  1 12]
Subtracted Array:
 [[ -7 -10  -7  -1]
 [ -8  -3  -7  -2]
 [ 13   1   3  15]
 [  0  -3  -5 -11]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [19]:
#
matrix = np.random.randint(1, 10, size=(3,3))
print("Matrix:\n", matrix)

## Computing Determinant
# determinant = 0 means matrix is not invertible
determinant = np.linalg.det(matrix)
print("Determinant:\n", determinant)

## Computing Inverse
# only works if determinant is not zero
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)

## Computing Eigenvalues
# eigenvalues show how the matrix scales space
eigen = np.linalg.eigvals(matrix)
print("Eigenvalues:\n", eigen)


Matrix:
 [[1 2 2]
 [6 9 2]
 [5 8 4]]
Determinant:
 -1.9999999999999922
Inverse:
 [[-10.   -4.    7. ]
 [  7.    3.   -5. ]
 [ -1.5  -1.    1.5]]
Eigenvalues:
 [13.15206735+0.j -0.15206735+0.j  1.        +0.j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [20]:
## 2 Numpy Arrays
ar1 = np.random.randint(1, 11, size=(2, 3))
ar2 = np.random.randint(1, 11, size=(3, 2))
print("First Array:\n", ar1)
print("Second Array:\n", ar2)

## Matrix Multiplication
mult = np.dot(ar1, ar2)
print("Matrix Multiplication Result:\n", mult)

First Array:
 [[ 8  7 10]
 [ 5 10  3]]
Second Array:
 [[9 3]
 [1 4]
 [9 2]]
Matrix Multiplication Result:
 [[169  72]
 [ 82  61]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [22]:
## Creating Array
arr = np.arange(1, 10).reshape((3, 3))
print("Original Array:\n", arr)

## Reshaped Array (1, 9)
reshape = arr.reshape((1, 9))
print("Reshaped array (1, 9):\n", reshape)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshape.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array (1, 9):
 [[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [23]:
## Array of shape (5, 5)
array = np.random.randint(1, 26, size=(5, 5))
print("Original Array:\n", array)

## Flatten the array
flat = array.flatten()
print("Flattened Array:\n", flat)

## Reshape back to (5,5)
reshaped = flat.reshape((5, 5))
print("Reshaped Array:\n", reshaped)

Original Array:
 [[24  5 16  4  3]
 [16 15 19 20 12]
 [ 2  8 25  6 21]
 [19 15 25  6  8]
 [ 3 14  9 13 17]]
Flattened Array:
 [24  5 16  4  3 16 15 19 20 12  2  8 25  6 21 19 15 25  6  8  3 14  9 13
 17]
Reshaped Array:
 [[24  5 16  4  3]
 [16 15 19 20 12]
 [ 2  8 25  6 21]
 [19 15 25  6  8]
 [ 3 14  9 13 17]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [29]:
## Random Numpy array (5,5)
array = np.random.randint(1, 21, size=(5, 5))
print("Original Array:\n", array)

## Extracting Elements at the corner of the Array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original Array:
 [[16  4  9 13 10]
 [ 5  9  5  8 14]
 [ 3  2 14 16  8]
 [11  7 11  7  3]
 [ 2 19  1  5 11]]
Corner elements:
[16 10  2 11]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [30]:
## Numpy array (4,4)
array = np.random.randint(1, 17, size=(4, 4))
print("Original Array:\n", array)

## Boolean to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified Array:\n", array)


Original Array:
 [[16 12 16  6]
 [16 10 12 10]
 [12  3  7 16]
 [ 8  1 13  8]]
Modified Array:
 [[10 10 10  6]
 [10 10 10 10]
 [10  3  7 10]
 [ 8  1 10  8]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [ ]:
##
# It defines a NumPy structured data type with three fields:
#  a string name (max 10 chars), a 32‑bit integer age, and a 32‑bit float weight.
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original Array")
print(data)

## Sort the Array by age
sorted_data = np.sort(data, order="age")
print("Sorted Array")
print(sorted_data)

Original Array
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted Array
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [37]:
## 
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
dist = np.sqrt(
    (data['x'][:, np.newaxis] - data['x'])**2 + # Squared X differences
    (data['y'][:, np.newaxis] - data['y'])**2)  # Squared Y differences
print("Euclidean distances:")
print(dist)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [38]:
## 
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 2  2 20  3]
 [14  3  2  8]
 [ 5 11  5  5]
 [15  6  2 16]]
Masked array:
[[2 2 -- 3]
 [-- 3 2 8]
 [5 -- 5 5]
 [-- 6 2 --]]
Sum of unmasked elements: 43


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [39]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 5  6 20]
 [ 1 11  7]
 [10  4 12]]
Masked array:
[[-- 6 20]
 [1 -- 7]
 [10 4 --]]
Modified masked array:
[[ 8  6 20]
 [ 1  8  7]
 [10  4  8]]
